### ISSUE TITLE
Explicit Loadiine version number

### ISSUE THREAD

**Issue by enron92** [EclipseSin/EclipseSin.github.io#1]
I would specify explicitly Loadiine version number on index page instead of an ambiguos "vLatest".
Reference [here](https://github.com/EclipseSin/EclipseSin.github.io/blob/c87bf3296ee289b8c0434ac6a23e712c91494413/index.html#L53).

Apart from that, excellent work!

**Comment by EclipseSin** [comment]
vLatest is not ambiguous. It means exactly what it says. It is always (or asap) the latest release version. Whether others can be bothered to find out what the latest version number is or isn't, is not a problem I need to address on the page. 

I have no plans to change this.
